[package]
name = "decalque"
version.workspace = true
edition.workspace = true

[[bin]]
name = "decalque"
path = "src/main.rs"

[[bin]]
name = "decalque-font-catalog"
path = "src/bin/font_catalog.rs"

[dependencies]
decalque-core = { path = "../01_core" }
decalque-shell = { path = "../02_shell" }
decalque-infra = { path = "../03_infra" }
