#!/usr/bin/env python3
# Crystalline Lineage
# @prompt _lab/scan_observer/specs/editorial-typst-composition.md
"""Compose classified page regions through a reusable Typst editorial library."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
import unicodedata
from pathlib import Path
from typing import Any

from PIL import Image, ImageChops, ImageFont, ImageStat


KNOWN_ROLES = {
    "heading", "body_paragraph", "epigraph", "verse_or_title_list", "block_quote",
    "biographical_note", "figure_caption", "page_number", "visual", "table", "unknown",
}


EDITORIAL_LIBRARY = r'''// Shared editorial primitives generated by editorial_typst_composer.py.
#let role-color(role) = if role == "unknown" { rgb("9b5c00") } else { black }

#let editorial-line(role: "body_paragraph", width: auto, family: "serif", size: 10pt,
  weight: "regular", style: "normal", tracking: 0pt, content: none) = {
  set text(font: family, size: size, weight: weight, style: style,
    tracking: tracking, fill: role-color(role), hyphenate: false)
  // `width` remains an observed audit anchor. It must not deform the glyphs.
  box(clip: false, content)
}

#let reserved-visual(label: "reserved visual", width: auto, height: auto, asset: none) = {
  if asset == none {
    rect(width: width, height: height, stroke: (paint: rgb("8a8a8a"), dash: "dashed"),
      inset: 4pt, align(center + horizon, text(7pt, fill: rgb("666666"), label)))
  } else {
    image(asset, width: width, height: height, fit: "stretch")
  }
}
'''


def _bbox(value: Any, name: str) -> list[float]:
    if not isinstance(value, list) or len(value) != 4:
        raise ValueError(f"{name} deve conter quatro números")
    result = [float(item) for item in value]
    if result[2] <= result[0] or result[3] <= result[1]:
        raise ValueError(f"{name} degenerada")
    return result


def _num(value: float) -> str:
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _role(region: dict[str, Any]) -> str:
    editorial = region.get("editorial_role") or {}
    role = editorial.get("role", "unknown")
    status = editorial.get("status", "unknown")
    if role != "unknown" and status != "observed":
        raise ValueError(f"papel editorial não observado: {region.get('id', '?')}")
    return role


def _nearest_visual(region: dict[str, Any], visuals: list[dict[str, Any]]) -> str | None:
    if not visuals:
        return None
    box = _bbox(region["bbox"], "region.bbox")
    center = ((box[0] + box[2]) / 2, (box[1] + box[3]) / 2)
    return min(visuals, key=lambda item: (
        abs(center[1] - (_bbox(item["bbox"], "visual.bbox")[1] +
                         _bbox(item["bbox"], "visual.bbox")[3]) / 2),
        abs(center[0] - (_bbox(item["bbox"], "visual.bbox")[0] +
                         _bbox(item["bbox"], "visual.bbox")[2]) / 2),
    )).get("id")


def build_manifest(classified: dict[str, Any], source_image: Path | None,
                   width_pt: float, height_pt: float, family: str,
                   page_number: int = 1) -> dict[str, Any]:
    page = classified.get("page", {})
    width_px = float(page.get("width_px", 0))
    height_px = float(page.get("height_px", 0))
    if min(width_px, height_px, width_pt, height_pt) <= 0:
        raise ValueError("dimensões da página devem ser positivas")
    regions = classified.get("regions")
    if not isinstance(regions, list):
        raise ValueError("regions deve ser uma lista")
    ordered = sorted(regions, key=lambda item: (_bbox(item["bbox"], "region.bbox")[1],
                                                _bbox(item["bbox"], "region.bbox")[0]))
    visuals = [item for item in ordered if _role(item) in {"visual", "table"}]
    blocks = []
    previous_bottom = 0.0
    for region in ordered:
        box = _bbox(region["bbox"], "region.bbox")
        role = _role(region)
        style = region.get("font_style_summary") or {}
        strategy = "reserved_visual" if role in {"visual", "table"} else (
            "unknown" if role == "unknown" else "text")
        lines = []
        for line in region.get("lines", []):
            text = str(line.get("text", "")).strip()
            if not text:
                raise ValueError(f"linha sem texto em {region.get('id', '?')}")
            lines.append({"text": text, "bbox_px": _bbox(line.get("bbox"), "line.bbox")})
        if strategy == "text" and not lines:
            raise ValueError(f"bloco textual sem linhas: {region.get('id', '?')}")
        block = {
            "id": region.get("id"), "role": role, "strategy": strategy,
            "bbox_px": box, "space_before_px": max(0.0, box[1] - previous_bottom),
            "lines": lines,
            "typography": {
                "family": family,
                "weight": style.get("weight", "regular") if style.get("weight") in
                          {"light", "regular", "medium", "semibold", "bold"} else "regular",
                "style": "italic" if style.get("slant") == "italic" else "normal",
                "status": style.get("status", "unknown"),
            },
        }
        if role == "figure_caption":
            block["related_visual_id"] = _nearest_visual(region, visuals)
        blocks.append(block)
        previous_bottom = max(previous_bottom, box[3])
    return {
        "schema_version": 1,
        "page": {"number": page_number, "side": "left" if page_number % 2 == 0 else "right",
                 "width_pt": width_pt, "height_pt": height_pt,
                 "source_width_px": width_px, "source_height_px": height_px,
                 "source_image": str(source_image.resolve()) if source_image else None},
        "blocks": blocks,
        "policy": {"physical_lines_frozen": True, "unknown_is_not_body": True,
                   "visual_geometry_reserved": True},
    }


def materialize(manifest: dict[str, Any]) -> str:
    page = manifest["page"]
    sx = page["width_pt"] / page["source_width_px"]
    sy = page["height_pt"] / page["source_height_px"]
    out = [
        '#import "editorial-blocks.typ": *',
        f'#set page(width: {_num(page["width_pt"])}pt, height: {_num(page["height_pt"])}pt, margin: 0pt)',
    ]
    for block in manifest["blocks"]:
        box = block["bbox_px"]
        x, y = box[0] * sx, box[1] * sy
        width, height = (box[2] - box[0]) * sx, (box[3] - box[1]) * sy
        if block["strategy"] == "reserved_visual":
            asset = block.get("asset")
            asset_arg = f", asset: {_string(asset)}" if asset else ""
            body = (f'#reserved-visual(label: {_string(block["role"] + " " + str(block["id"]))}, '
                    f'width: {_num(width)}pt, height: {_num(height)}pt{asset_arg})')
            out.append(f'#place(top + left, dx: {_num(x)}pt, dy: {_num(y)}pt)[{body}]')
            continue
        typography = block["typography"]
        for line in block["lines"]:
            line_box = line["bbox_px"]
            lx, ly = line_box[0] * sx, line_box[1] * sy
            lw, lh = (line_box[2] - line_box[0]) * sx, (line_box[3] - line_box[1]) * sy
            size = max(5.0, lh * 0.80)
            safe_text = _string(line["text"])
            body = (f'#editorial-line(role: {_string(block["role"])}, width: {_num(lw)}pt, '
                    f'family: {_string(typography["family"])}, size: {_num(size)}pt, '
                    f'weight: {_string(typography["weight"])}, style: {_string(typography["style"])}, '
                    f'content: text({safe_text}))')
            out.append(f'#place(top + left, dx: {_num(lx)}pt, dy: {_num(ly)}pt)[{body}]')
    return "\n\n".join(out) + "\n"


def _run(args: list[str], label: str) -> str:
    process = subprocess.run(args, capture_output=True, text=True, check=False)
    if process.returncode:
        raise RuntimeError(process.stderr.strip() or f"{label} falhou")
    return process.stdout


def _searchable_words(value: str) -> str:
    value = unicodedata.normalize("NFKD", value).lower()
    value = value.translate(str.maketrans({"’": "'", "‘": "'", "“": '"', "”": '"'}))
    # Some PDF extractors expose a font ligature as a separated leading letter ("f lash").
    value = re.sub(r"f\s+(?=[a-z])", "f", value)
    return " ".join(re.findall(r"[a-z0-9]+", value))


def compose(classified_path: Path, source_path: Path, output_dir: Path, font_path: Path,
            width_pt: float, height_pt: float, page_number: int, dpi: int) -> dict[str, Any]:
    started = time.perf_counter()
    timings: dict[str, float] = {}
    if not font_path.is_file():
        raise ValueError(f"fonte não encontrada: {font_path}")
    classified = json.loads(classified_path.read_text(encoding="utf-8"))
    family = ImageFont.truetype(str(font_path), 20).getname()[0]
    manifest = build_manifest(classified, source_path, width_pt, height_pt, family, page_number)
    timings["load_and_manifest"] = time.perf_counter() - started
    output_dir.mkdir(parents=True, exist_ok=True)
    assets = output_dir / "assets"
    stage = time.perf_counter()
    with Image.open(source_path).convert("RGB") as source:
        expected = (round(manifest["page"]["source_width_px"]),
                    round(manifest["page"]["source_height_px"]))
        if source.size != expected:
            raise ValueError(f"imagem {source.size} difere da geometria classificada {expected}")
        for block in manifest["blocks"]:
            if block["strategy"] != "reserved_visual":
                continue
            assets.mkdir(exist_ok=True)
            target = assets / f'{block["id"]}.png'
            source.crop(tuple(round(value) for value in block["bbox_px"])).save(target)
            block["asset"] = str(target.resolve())
    timings["crop_visuals"] = time.perf_counter() - stage
    stage = time.perf_counter()
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    (output_dir / "editorial-blocks.typ").write_text(EDITORIAL_LIBRARY, encoding="utf-8")
    typ_path = output_dir / "page.typ"
    typ_path.write_text(materialize(manifest), encoding="utf-8")
    timings["write_sources"] = time.perf_counter() - stage
    pdf_path = output_dir / "page.pdf"
    stage = time.perf_counter()
    _run(["typst", "compile", "--root", "/", "--font-path", str(font_path.parent),
          str(typ_path), str(pdf_path)], "compilação Typst")
    timings["typst_compile"] = time.perf_counter() - stage
    png_prefix = output_dir / "page"
    stage = time.perf_counter()
    _run(["pdftoppm", "-f", "1", "-l", "1", "-singlefile", "-r", str(dpi),
          "-png", str(pdf_path), str(png_prefix)], "rasterização")
    timings["pdf_rasterize"] = time.perf_counter() - stage
    rendered_path = png_prefix.with_suffix(".png")
    stage = time.perf_counter()
    with Image.open(source_path).convert("RGB") as source, Image.open(rendered_path).convert("RGB") as rendered:
        reference = source.resize(rendered.size, Image.Resampling.LANCZOS)
        difference = ImageChops.difference(reference, rendered)
        difference.save(output_dir / "comparison.png")
        mae = sum(ImageStat.Stat(difference).mean) / (3 * 255)
    timings["raster_diff"] = time.perf_counter() - stage
    stage = time.perf_counter()
    extracted = _searchable_words(_run(["pdftotext", "-layout", str(pdf_path), "-"], "extração"))
    expected_text = [line["text"] for block in manifest["blocks"] for line in block["lines"]]
    missing = [text for text in expected_text if _searchable_words(text) not in extracted]
    timings["text_verify"] = time.perf_counter() - stage
    timings["total"] = time.perf_counter() - started
    report = {"schema_version": 1, "status": "success" if not missing else "partial",
              "block_count": len(manifest["blocks"]), "text_line_count": len(expected_text),
              "reserved_visual_count": sum(b["strategy"] == "reserved_visual" for b in manifest["blocks"]),
              "missing_text_lines": missing, "mean_absolute_error": round(mae, 6),
              "pdf": str(pdf_path.resolve()), "manifest": str(manifest_path.resolve()),
              "timings_seconds": {key: round(value, 6) for key, value in timings.items()}}
    (output_dir / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("classified", type=Path)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--width-pt", type=float, default=452.16)
    parser.add_argument("--height-pt", type=float, default=714.24)
    parser.add_argument("--page-number", type=int, default=1)
    parser.add_argument("--dpi", type=int, default=150)
    args = parser.parse_args()
    try:
        print(json.dumps(compose(args.classified, args.source, args.output_dir, args.font,
                                 args.width_pt, args.height_pt, args.page_number, args.dpi),
                         ensure_ascii=False, indent=2))
        return 0
    except Exception as error:
        print(f"editorial-typst-composer: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
